<?php

namespace App\OpenApi;

/**
 * @OA\Tag(name="Auth")
 * @OA\Tag(name="Notifications")
 * @OA\Tag(name="Dashboard")
 * @OA\Tag(name="Permissions")
 * @OA\Tag(name="Roles")
 * @OA\Tag(name="Staff")
 * @OA\Tag(name="Clients")
 * @OA\Tag(name="Vendors")
 * @OA\Tag(name="Renewals")
 * @OA\Tag(name="Todos")
 * @OA\Tag(name="Leads")
 * @OA\Tag(name="Meta Leads")
 * @OA\Tag(name="Projects")
 * @OA\Tag(name="Tasks")
 * @OA\Tag(name="Client Issues")
 * @OA\Tag(name="Services")
 * @OA\Tag(name="Calendar")
 * @OA\Tag(name="Settings")
 * @OA\Tag(name="Book a Call")
 * @OA\Tag(name="Google Ads")
 * @OA\Tag(name="Google Ads Leads")
 * @OA\Tag(name="Webhooks")
 *
 * @OA\SecurityScheme(
 *     securityScheme="sanctum",
 *     type="http",
 *     scheme="bearer",
 *     bearerFormat="Token"
 * )
 *
 * Public Auth and Auth Profile routes are documented in AuthController annotations.
 * @OA\Post(path="/api/v1/test-fcm", tags={"Auth"}, summary="Test FCM", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 *
 * Notifications
 * @OA\Get(path="/api/v1/notifications", tags={"Notifications"}, summary="List notifications", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Patch(path="/api/v1/notifications/{id}/read", tags={"Notifications"}, summary="Mark notification read", security={{"sanctum":{}}}, @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")), @OA\Response(response=200, description="OK"))
 * @OA\Patch(path="/api/v1/notifications/read-all", tags={"Notifications"}, summary="Mark all notifications read", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 *
 * Dashboard routes are documented in DashboardController annotations.
 *
 * Permissions and Roles
 * @OA\Get(path="/api/v1/permissions", tags={"Permissions"}, summary="Permissions list", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/permissions/grouped", tags={"Permissions"}, summary="Grouped permissions", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/roles", tags={"Roles"}, summary="Roles list", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Post(path="/api/v1/roles", tags={"Roles"}, summary="Create role", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Put(path="/api/v1/roles/{id}", tags={"Roles"}, summary="Update role", security={{"sanctum":{}}}, @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")), @OA\Response(response=200, description="OK"))
 * @OA\Patch(path="/api/v1/roles/{id}", tags={"Roles"}, summary="Partially update role", security={{"sanctum":{}}}, @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")), @OA\Response(response=200, description="OK"))
 * @OA\Delete(path="/api/v1/roles/{id}", tags={"Roles"}, summary="Delete role", security={{"sanctum":{}}}, @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")), @OA\Response(response=200, description="OK"))
 *
 * Staff + Staff V2
 * @OA\Get(path="/api/v1/staff/form-options", tags={"Staff"}, summary="Staff form options", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/staff", tags={"Staff"}, summary="Staff list", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Post(path="/api/v1/staff", tags={"Staff"}, summary="Create staff", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/staff/{id}", tags={"Staff"}, summary="Staff detail", security={{"sanctum":{}}}, @OA\Parameter(name="id", in="path", required=true, @OA\Schema(type="integer")), @OA\Response(response=200, description="OK"))
 * @OA\Put(path="/api/v1/staff/{id}", tags={"Staff"}, summary="Update staff", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Patch(path="/api/v1/staff/{id}", tags={"Staff"}, summary="Partial update staff", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Delete(path="/api/v1/staff/{id}", tags={"Staff"}, summary="Delete staff", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Post(path="/api/v1/staff/{id}/restore", tags={"Staff"}, summary="Restore staff", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Delete(path="/api/v1/staff/{id}/force", tags={"Staff"}, summary="Force delete staff", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/staff/{id}/tasks", tags={"Staff"}, summary="Staff tasks", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/staff/{id}/projects", tags={"Staff"}, summary="Staff projects", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/staff-v2/departments", tags={"Staff"}, summary="Staff v2 departments", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/staff-v2/teams", tags={"Staff"}, summary="Staff v2 teams", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/staff-v2/form-options", tags={"Staff"}, summary="Staff v2 form options", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/staff-v2/{id}/analytics", tags={"Staff"}, summary="Staff v2 analytics", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/staff-v2/{id}/lead-chart", tags={"Staff"}, summary="Staff v2 lead chart", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/staff-v2/{id}/followup-chart", tags={"Staff"}, summary="Staff v2 followup chart", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/staff-v2", tags={"Staff"}, summary="Staff v2 list", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Post(path="/api/v1/staff-v2", tags={"Staff"}, summary="Create staff v2", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/staff-v2/{id}", tags={"Staff"}, summary="Staff v2 detail", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Put(path="/api/v1/staff-v2/{id}", tags={"Staff"}, summary="Update staff v2", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Delete(path="/api/v1/staff-v2/{id}", tags={"Staff"}, summary="Delete staff v2", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Post(path="/api/v1/staff-v2/{id}/restore", tags={"Staff"}, summary="Restore staff v2", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Delete(path="/api/v1/staff-v2/{id}/force", tags={"Staff"}, summary="Force delete staff v2", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 *
 * Clients / Vendors / Renewals
 * @OA\Get(path="/api/v1/clients", tags={"Clients"}, summary="Clients list", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Post(path="/api/v1/clients", tags={"Clients"}, summary="Create client", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/clients/{id}", tags={"Clients"}, summary="Client detail", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Put(path="/api/v1/clients/{id}", tags={"Clients"}, summary="Update client", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Patch(path="/api/v1/clients/{id}", tags={"Clients"}, summary="Partial update client", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Delete(path="/api/v1/clients/{id}", tags={"Clients"}, summary="Delete client", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/vendors", tags={"Vendors"}, summary="Vendors list", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Post(path="/api/v1/vendors", tags={"Vendors"}, summary="Create vendor", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/vendors/{id}", tags={"Vendors"}, summary="Vendor detail", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Put(path="/api/v1/vendors/{id}", tags={"Vendors"}, summary="Update vendor", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Patch(path="/api/v1/vendors/{id}", tags={"Vendors"}, summary="Partial update vendor", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Delete(path="/api/v1/vendors/{id}", tags={"Vendors"}, summary="Delete vendor", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/vendor-renewals", tags={"Renewals"}, summary="Vendor renewals list", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Post(path="/api/v1/vendor-renewals", tags={"Renewals"}, summary="Create vendor renewal", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/vendor-renewals/{id}", tags={"Renewals"}, summary="Vendor renewal detail", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Put(path="/api/v1/vendor-renewals/{id}", tags={"Renewals"}, summary="Update vendor renewal", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Delete(path="/api/v1/vendor-renewals/{id}", tags={"Renewals"}, summary="Delete vendor renewal", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/client-renewals/form-options", tags={"Renewals"}, summary="Client renewals form options", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/client-renewals", tags={"Renewals"}, summary="Client renewals list", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Post(path="/api/v1/client-renewals", tags={"Renewals"}, summary="Create client renewal", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/client-renewals/{id}", tags={"Renewals"}, summary="Client renewal detail", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Put(path="/api/v1/client-renewals/{id}", tags={"Renewals"}, summary="Update client renewal", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Delete(path="/api/v1/client-renewals/{id}", tags={"Renewals"}, summary="Delete client renewal", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 *
 * Todos / Leads / Meta Leads
 * @OA\Get(path="/api/v1/todos", tags={"Todos"}, summary="Todos list", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Post(path="/api/v1/todos", tags={"Todos"}, summary="Create todo", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/todos/{todo}", tags={"Todos"}, summary="Todo detail", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Put(path="/api/v1/todos/{todo}", tags={"Todos"}, summary="Update todo", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Patch(path="/api/v1/todos/{todo}", tags={"Todos"}, summary="Partial update todo", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Delete(path="/api/v1/todos/{todo}", tags={"Todos"}, summary="Delete todo", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/todos/options", tags={"Todos"}, summary="Todo options", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Patch(path="/api/v1/todos/{todo}/status", tags={"Todos"}, summary="Toggle todo status", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/leads/form-options", tags={"Leads"}, summary="Lead form options", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/leads/dashboard", tags={"Leads"}, summary="Lead dashboard", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/leads", tags={"Leads"}, summary="Leads list", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Post(path="/api/v1/leads", tags={"Leads"}, summary="Create lead", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/leads/{id}", tags={"Leads"}, summary="Lead detail", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Put(path="/api/v1/leads/{id}", tags={"Leads"}, summary="Update lead", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Patch(path="/api/v1/leads/{id}", tags={"Leads"}, summary="Partial update lead", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Delete(path="/api/v1/leads/{id}", tags={"Leads"}, summary="Delete lead", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/meta-leads", tags={"Meta Leads"}, summary="Meta leads list", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Post(path="/api/v1/meta-leads/sync", tags={"Meta Leads"}, summary="Sync meta leads", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/meta-leads/{lead}", tags={"Meta Leads"}, summary="Meta lead detail", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Delete(path="/api/v1/meta-leads/{lead}", tags={"Meta Leads"}, summary="Delete meta lead", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 *
 * Projects
 * @OA\Get(path="/api/v1/projects/form-options", tags={"Projects"}, summary="Project form options", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/projects", tags={"Projects"}, summary="Projects list", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Post(path="/api/v1/projects", tags={"Projects"}, summary="Create project", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/projects/{id}", tags={"Projects"}, summary="Project detail", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Put(path="/api/v1/projects/{id}", tags={"Projects"}, summary="Update project", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Patch(path="/api/v1/projects/{id}", tags={"Projects"}, summary="Partial update project", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Delete(path="/api/v1/projects/{id}", tags={"Projects"}, summary="Delete project", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/projects/{projectId}/details", tags={"Projects"}, summary="Project details dashboard", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/projects/{projectId}/milestones", tags={"Projects"}, summary="Project milestones", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Post(path="/api/v1/projects/{projectId}/milestones", tags={"Projects"}, summary="Create milestone", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Put(path="/api/v1/projects/{projectId}/milestones/{milestoneId}", tags={"Projects"}, summary="Update milestone", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Patch(path="/api/v1/projects/{projectId}/milestones/{milestoneId}", tags={"Projects"}, summary="Partial update milestone", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Delete(path="/api/v1/projects/{projectId}/milestones/{milestoneId}", tags={"Projects"}, summary="Delete milestone", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/projects/{projectId}/issues", tags={"Projects"}, summary="Project issues", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Post(path="/api/v1/projects/{projectId}/issues", tags={"Projects"}, summary="Create issue", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Put(path="/api/v1/projects/{projectId}/issues/{issueId}", tags={"Projects"}, summary="Update issue", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Patch(path="/api/v1/projects/{projectId}/issues/{issueId}", tags={"Projects"}, summary="Partial update issue", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Delete(path="/api/v1/projects/{projectId}/issues/{issueId}", tags={"Projects"}, summary="Delete issue", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/projects/{projectId}/comments", tags={"Projects"}, summary="Project comments", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Post(path="/api/v1/projects/{projectId}/comments", tags={"Projects"}, summary="Create project comment", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/projects/{projectId}/files", tags={"Projects"}, summary="Project files", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Post(path="/api/v1/projects/{projectId}/files", tags={"Projects"}, summary="Upload project file", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Delete(path="/api/v1/projects/{projectId}/files/{fileId}", tags={"Projects"}, summary="Delete project file", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/projects/{projectId}/usage", tags={"Projects"}, summary="Project usage", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 *
 * Tasks
 * @OA\Get(path="/api/v1/tasks/form-options", tags={"Tasks"}, summary="Task form options", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/tasks", tags={"Tasks"}, summary="Tasks list", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Post(path="/api/v1/tasks", tags={"Tasks"}, summary="Create task", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/tasks/{id}", tags={"Tasks"}, summary="Task detail", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Put(path="/api/v1/tasks/{id}", tags={"Tasks"}, summary="Update task", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Patch(path="/api/v1/tasks/{id}", tags={"Tasks"}, summary="Partial update task", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Delete(path="/api/v1/tasks/{id}", tags={"Tasks"}, summary="Delete task", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/tasks/{taskId}/comments", tags={"Tasks"}, summary="Task comments", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Post(path="/api/v1/tasks/{taskId}/comments", tags={"Tasks"}, summary="Create task comment", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/tasks/{taskId}/attachments", tags={"Tasks"}, summary="Task attachments", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Post(path="/api/v1/tasks/{taskId}/attachments", tags={"Tasks"}, summary="Upload task attachment", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Delete(path="/api/v1/tasks/{taskId}/attachments/{attachmentId}", tags={"Tasks"}, summary="Delete task attachment", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 *
 * Client Issues / Services / Calendar
 * @OA\Get(path="/api/v1/client-issues/form-options", tags={"Client Issues"}, summary="Client issue form options", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/client-issues", tags={"Client Issues"}, summary="Client issues list", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Post(path="/api/v1/client-issues", tags={"Client Issues"}, summary="Create client issue", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/client-issues/{id}", tags={"Client Issues"}, summary="Client issue detail", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Patch(path="/api/v1/client-issues/{id}/status", tags={"Client Issues"}, summary="Update client issue status", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Delete(path="/api/v1/client-issues/{id}", tags={"Client Issues"}, summary="Delete client issue", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Post(path="/api/v1/client-issues/{clientIssue}/assign", tags={"Client Issues"}, summary="Assign team", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Post(path="/api/v1/client-issues/{clientIssue}/tasks", tags={"Client Issues"}, summary="Create linked task", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/client-issues/{clientIssue}/tasks/{task}", tags={"Client Issues"}, summary="Linked task detail", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Put(path="/api/v1/client-issues/{clientIssue}/tasks/{task}", tags={"Client Issues"}, summary="Update linked task", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Patch(path="/api/v1/client-issues/{clientIssue}/tasks/{task}", tags={"Client Issues"}, summary="Partial update linked task", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Patch(path="/api/v1/client-issues/{clientIssue}/tasks/{task}/status", tags={"Client Issues"}, summary="Update linked task status", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Delete(path="/api/v1/client-issues/{clientIssue}/tasks/{task}", tags={"Client Issues"}, summary="Delete linked task", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/services/form-options", tags={"Services"}, summary="Service form options", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/services", tags={"Services"}, summary="Services list", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Post(path="/api/v1/services", tags={"Services"}, summary="Create service", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/services/{id}", tags={"Services"}, summary="Service detail", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Put(path="/api/v1/services/{id}", tags={"Services"}, summary="Update service", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Patch(path="/api/v1/services/{id}", tags={"Services"}, summary="Partial update service", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Delete(path="/api/v1/services/{id}", tags={"Services"}, summary="Delete service", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Post(path="/api/v1/services/delete-selected", tags={"Services"}, summary="Delete selected services", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/calendar/events", tags={"Calendar"}, summary="Calendar events list", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Post(path="/api/v1/calendar/events", tags={"Calendar"}, summary="Create calendar event", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/calendar/events/{id}", tags={"Calendar"}, summary="Calendar event detail", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Put(path="/api/v1/calendar/events/{id}", tags={"Calendar"}, summary="Update calendar event", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Patch(path="/api/v1/calendar/events/{id}", tags={"Calendar"}, summary="Partial update calendar event", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Delete(path="/api/v1/calendar/events/{id}", tags={"Calendar"}, summary="Delete calendar event", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 *
 * Settings / Book a Call / Google Ads / Google Lead API
 * @OA\Get(path="/api/v1/settings", tags={"Settings"}, summary="Settings index", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/settings/general", tags={"Settings"}, summary="Get general settings", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Post(path="/api/v1/settings/general", tags={"Settings"}, summary="Update general settings", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Put(path="/api/v1/settings/general", tags={"Settings"}, summary="Update general settings", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Patch(path="/api/v1/settings/general", tags={"Settings"}, summary="Partial update general settings", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/settings/company", tags={"Settings"}, summary="Get company settings", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Post(path="/api/v1/settings/company", tags={"Settings"}, summary="Update company settings", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Put(path="/api/v1/settings/company", tags={"Settings"}, summary="Update company settings", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Patch(path="/api/v1/settings/company", tags={"Settings"}, summary="Partial update company settings", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/settings/email", tags={"Settings"}, summary="Get email settings", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Post(path="/api/v1/settings/email", tags={"Settings"}, summary="Update email settings", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Put(path="/api/v1/settings/email", tags={"Settings"}, summary="Update email settings", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Patch(path="/api/v1/settings/email", tags={"Settings"}, summary="Partial update email settings", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/settings/renewal", tags={"Settings"}, summary="Get renewal settings", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Post(path="/api/v1/settings/renewal", tags={"Settings"}, summary="Update renewal settings", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Put(path="/api/v1/settings/renewal", tags={"Settings"}, summary="Update renewal settings", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Patch(path="/api/v1/settings/renewal", tags={"Settings"}, summary="Partial update renewal settings", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/settings/teams", tags={"Settings"}, summary="Get teams", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Post(path="/api/v1/settings/teams", tags={"Settings"}, summary="Update teams", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Put(path="/api/v1/settings/teams", tags={"Settings"}, summary="Update teams", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Patch(path="/api/v1/settings/teams", tags={"Settings"}, summary="Partial update teams", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/settings/departments", tags={"Settings"}, summary="Get departments", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Post(path="/api/v1/settings/departments", tags={"Settings"}, summary="Update departments", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Put(path="/api/v1/settings/departments", tags={"Settings"}, summary="Update departments", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Patch(path="/api/v1/settings/departments", tags={"Settings"}, summary="Partial update departments", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Post(path="/api/v1/settings/test-email", tags={"Settings"}, summary="Send test email", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/settings/search-tags", tags={"Settings"}, summary="Search tags", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/settings/app-logo", tags={"Settings"}, summary="Get app logo", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Post(path="/api/v1/settings/app-logo", tags={"Settings"}, summary="Update app logo", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Put(path="/api/v1/settings/app-logo", tags={"Settings"}, summary="Update app logo", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Patch(path="/api/v1/settings/app-logo", tags={"Settings"}, summary="Partial update app logo", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/settings/login-logo", tags={"Settings"}, summary="Get login logo", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Post(path="/api/v1/settings/login-logo", tags={"Settings"}, summary="Update login logo", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Put(path="/api/v1/settings/login-logo", tags={"Settings"}, summary="Update login logo", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Patch(path="/api/v1/settings/login-logo", tags={"Settings"}, summary="Partial update login logo", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/book-a-call", tags={"Book a Call"}, summary="Book-a-call list", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Delete(path="/api/v1/book-a-call/{id}", tags={"Book a Call"}, summary="Delete book-a-call", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/digital-marketing", tags={"Google Ads"}, summary="Digital marketing leads", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Delete(path="/api/v1/digital-marketing/{id}", tags={"Google Ads"}, summary="Delete digital marketing lead", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/web-apps-leads", tags={"Google Ads"}, summary="Web app leads", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Delete(path="/api/v1/web-apps-leads/{id}", tags={"Google Ads"}, summary="Delete web app lead", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/google-ads-leads", tags={"Google Ads Leads"}, summary="Google ads leads list", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/google-ads-leads/stats", tags={"Google Ads Leads"}, summary="Google ads leads stats", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/v1/google-ads-leads/{googleLead}", tags={"Google Ads Leads"}, summary="Google ads lead detail", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 *
 * Misc + Webhooks
 * @OA\Get(path="/api/user", tags={"Auth"}, summary="Authenticated user fallback", security={{"sanctum":{}}}, @OA\Response(response=200, description="OK"))
 * @OA\Get(path="/api/facebook/webhook", tags={"Webhooks"}, summary="Verify Facebook webhook", @OA\Response(response=200, description="OK"))
 * @OA\Post(path="/api/facebook/webhook", tags={"Webhooks"}, summary="Handle Facebook webhook", @OA\Response(response=200, description="OK"))
 * @OA\Post(path="/api/google-ads/lead", tags={"Webhooks"}, summary="Receive Google Ads lead webhook", @OA\Response(response=200, description="OK"))
 */
class ApiRoutesAnnotations {}
